package com.haizhi.sms.topen;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "MsgSend", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://122.144.130.36:1210/Services/MsgSend.asmx?WSDL")
public class MsgSend extends Service {

    private static URL MSGSEND_WSDL_LOCATION;
    private static WebServiceException MSGSEND_EXCEPTION;
    private static QName MSGSEND_QNAME = new QName("http://tempuri.org/", "MsgSend");

    public static void init(Properties properties) {
        URL url = null;
        WebServiceException e = null;
        try {
            String endpoint = properties.getProperty("topen.sms.endpoint");
            if (endpoint == null) {
                // TODO log error
            }
            if (!endpoint.endsWith("/")) {
                endpoint += "/";
            }
            url = new URL(endpoint + "Services/MsgSend.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MSGSEND_WSDL_LOCATION = url;
        MSGSEND_EXCEPTION = e;
    }

    public MsgSend() {
        super(__getWsdlLocation(), MSGSEND_QNAME);
    }

    public MsgSend(WebServiceFeature... features) {
        super(__getWsdlLocation(), MSGSEND_QNAME, features);
    }

    public MsgSend(URL wsdlLocation) {
        super(wsdlLocation, MSGSEND_QNAME);
    }

    public MsgSend(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MSGSEND_QNAME, features);
    }

    public MsgSend(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MsgSend(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns MsgSendSoap
     */
    @WebEndpoint(name = "MsgSendSoap")
    public MsgSendSoap getMsgSendSoap() {
        return super.getPort(new QName("http://tempuri.org/", "MsgSendSoap"), MsgSendSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns MsgSendSoap
     */
    @WebEndpoint(name = "MsgSendSoap")
    public MsgSendSoap getMsgSendSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "MsgSendSoap"), MsgSendSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MSGSEND_EXCEPTION != null) {
            throw MSGSEND_EXCEPTION;
        }
        return MSGSEND_WSDL_LOCATION;
    }

}
